### ISSUE TITLE
ERROR: Nothing RPROVIDES 'linux-firmware-atmel'

### ISSUE THREAD

**Issue by kechap** [thorrockstar/meta-thornxt#1] opened 2018-08-03 08:42 UTC
I am trying to build an image using this layer but I get the following.

> vmif@ubuntu:~/thor/yocto/poky/build-atmel$ bitbake atmel-xplained-demo-image
> Parsing recipes: 100% |###############################################################################| Time: 0:01:07
> Parsing of 1975 .bb files complete (0 cached, 1975 parsed). 2683 targets, 339 skipped, 0 masked, 0 errors.
> NOTE: Resolving any missing task queue dependencies
> ERROR: Nothing RPROVIDES 'linux-firmware-atmel' (but /home/vmif/thor/yocto/meta-atmel/recipes-atmel/images/atmel-xplained-demo-image.bb RDEPENDS on or otherwise requires it)
> NOTE: Runtime target 'linux-firmware-atmel' is unbuildable, removing...
> Missing or unbuildable dependency chain was: ['linux-firmware-atmel']
> ERROR: Required build target 'atmel-xplained-demo-image' has no buildable providers.
> Missing or unbuildable dependency chain was: ['atmel-xplained-demo-image', 'linux-firmware-atmel']
> 
> Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
> 

Is the following really needed (atmel-xplained-demo-image.bbappend)?
```
linux-firmware-atmel \
linux-firmware-atmel-license \
```

**Comment by thorrockstar** [comment] 2018-08-03 20:04
Hi,

It seems that you are simply missing the Atmel layer. This layer is necessary if building the image for our board. Our layer builds on top of the Atmel layer. So check which release of Yocto, Atmel is currently supporting. For that look at the AT91 website. If you check out a Yocto version higher than supported by the Atmel layer yet, you will run into that issue.

Roy

Gesendet mit meinem HTC

----- Nachricht beantworten -----
Von: "Kechagias Apostolos" <notifications@github.com>
An: "thorrockstar/meta-thornxt" <meta-thornxt@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [thorrockstar/meta-thornxt] ERROR: Nothing RPROVIDES 'linux-firmware-atmel' (#1)
Datum: Fr., Aug. 3, 2018 10:42

I am trying to build an image using this layer but I get the following.

vmif@ubuntu:~/thor/yocto/poky/build-atmel$ bitbake atmel-xplained-demo-image

Parsing recipes: 100% |###############################################################################| Time: 0:01:07

Parsing of 1975 .bb files complete (0 cached, 1975 parsed). 2683 targets, 339 skipped, 0 masked, 0 errors.

NOTE: Resolving any missing task queue dependencies

ERROR: Nothing RPROVIDES 'linux-firmware-atmel' (but /home/vmif/thor/yocto/meta-atmel/recipes-atmel/images/atmel-xplained-demo-image.bb RDEPENDS on or otherwise requires it)

NOTE: Runtime target 'linux-firmware-atmel' is unbuildable, removing...

Missing or unbuildable dependency chain was: ['linux-firmware-atmel']

ERROR: Required build target 'atmel-xplained-demo-image' has no buildable providers.

Missing or unbuildable dependency chain was: ['atmel-xplained-demo-image', 'linux-firmware-atmel']
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

Is the following really needed (atmel-xplained-demo-image.bbappend)?
linux-firmware-atmel \
linux-firmware-atmel-license \


&mdash;You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by thorrockstar** [comment] 2018-08-03 21:24
Hi again,

By the way, when configuring the kernel, make sure (I really mean it) 
that the kernel setting 'General Setup -> Timers subsystem -> Timer tick 
handling: Periodic timer ticks (constant rate)' has been set - see 
screenshot.

If you forget this, you end up with wrong CPU load values shown in 'top' 
and other ugly side effects that needs to be avoided. Unfortunately 
since Morty the default setting is wrong here. So again, check that it 
is set to Periodic, constant rate. This is what we need in our embedded 
design.

Double check that our CAN-driver patches are include - they are absolute 
mandatory. The last update to this patches was done for Yocto Morty. The 
patch basically adds a Micro-Fifo in the interrupt handler as the SAM5D3 
has little CAN message boxes. Without this patch the communication at 
CAN1 (drive system and encoder system) will not run correctly. The patch 
also disables interrupt triggering for error frames.

Kind regards

Am 03.08.2018 um 10:42 schrieb Kechagias Apostolos:

**Comment by kechap** [comment] 2018-08-05 08:03
Thanks for the tips. 

I tried to build the layer using rocko and morty and I ended up into the same issue. Are you able to reproduce it?

**Comment by thorrockstar** [comment] 2018-08-05 13:30
Hi,

I have build my Morty image a while ago that we are using for production 
- and we do produce now a lot. :-) Using that check out I can't 
reproduce it. But I think you can remove the Atmel license and firmware 
dependency. The 'firmware' is usually software/drivers for components 
not build directly into the kernel and can be found under 
'/lib/firmware/'. So try to remove both dependencies. All the boards 
needs for its on-board components is build in the kernel.

Here you find some DropBox links to my bblayers, local.conf and 
atmel-xplained-demo-image.bbappend files. Just do a diff to ensure it is 
nothing in there. I dropped my Danish college an e-mail as he is using 
the image for the new TFT-display he is working on. Maybe he had that 
issue before when building the image.

https://www.dropbox.com/s/8ps1dpyptbfnmny/bblayers.conf?dl=0

https://www.dropbox.com/s/wgppkf5yrhc362x/local.conf?dl=0

https://www.dropbox.com/s/e3y1kfx0wkt2fp1/atmel-xplained-demo-image.bbappend?dl=0

Kind regards

Roy

Am 05.08.2018 um 10:03 schrieb Kechagias Apostolos:

**Comment by thorrockstar** [comment] 2018-08-05 13:41
Hi,

and here the image build files as well. Just do a diff - something in 
here might differ, especially in the Include file (*.inc).

https://www.dropbox.com/s/f6galjoa5jbfv2v/atmel-demo-image.inc?dl=0

https://www.dropbox.com/s/t0k7t9mn6zeoxxr/atmel-xplained-demo-image.bb?dl=0


Kind regards


Am 05.08.2018 um 10:03 schrieb Kechagias Apostolos:

**Comment by thorrockstar** [comment] 2018-08-05 14:25
Hi,

have you double checked that it is really the very same Morty release? 
If it is a newer release then they might have changed a few bits & 
details in the last minute. I mean DISTRO_VERSION and meta-atmel hash. 
But again, as all our drivers are build-in, you should try to remove the 
two 'atmel-firmware' dependencies. I guess you will find a difference in 
the atmel-demo-image.inc file I provided you and the one you are using. 
If yes, please let me know what it was, so I can update our layer as 
well. By the way, I have not created a branch for rocko so long. I will 
do in autumn this year.  
  
    Build Configuration:
    BB_VERSION        = "1.32.0"
    BUILD_SYS         = "i686-linux"
    NATIVELSBSTRING   = "Ubuntu-16.04"
    TARGET_SYS        = "arm-poky-linux-gnueabi"
    MACHINE           = "sama5d3-xplained"
    DISTRO            = "poky-atmel"
    DISTRO_VERSION    = "2.2.2"
    TUNE_FEATURES     = "arm armv7a vfp thumb            callconvention-hard            cortexa5"
    TARGET_FPU        = "hard"
    meta              
    meta-poky         
    meta-yocto-bsp    = "morty:d05941ae4567def4a288894717e5f550da246107"
    meta-atmel        = "morty:8c79606d3e73179506a6bbc40406f2c3aa9bf40e"
    meta-thornxt      = "morty:824b7b7d95d1837806d9c9c454ae02ba6550968b"
    meta-oe           
    meta-networking   
    meta-python       = "morty:fe5c83312de11e80b85680ef237f8acb04b4b26e"
    meta-qt5          = "morty:3601fd2c5306ac6d5d0d536e0be8cbb90da9b4c1"

Kind regards

Roy

Am 05.08.2018 um 10:03 schrieb Kechagias Apostolos:

**Comment by thorrockstar** [comment] 2018-08-05 16:26
Hi again,

as you can see in the thor-nxt branch 'morty' documentation (build log), 
I used DISTRO 2.2.2. But if you now check out 'morty', you will end up 
with a distro slightly newer 2.2.*4* and there is a slightly difference 
here. Using these steps, I could reproduce your problem - that is good 
news. :-)

I have now fixed the receipt in the 'morty' branch of our layer 
'meta-thornxt' that caused the issue. Thanks for your feedback. You are 
welcome.

Please give me some feedback if the issue is solved for you now as well.

Here are the *exact steps* required to build the image now. Don't forget 
to setup your CROSS-compiler as mentioned below. :-)

	> mkdir poky
         > cd poky
              

	> git clone git://git.yoctoproject.org/poky -b morty

	> git clone git://git.openembedded.org/meta-openembedded -b morty

	> git clone git://github.com/meta-qt5/meta-qt5.git -b morty

	> git clone git://github.com/linux4sam/meta-atmel.git -b morty

	> git clone git://github.com/thorrockstar/meta-thornxt.git -b morty

	> cd poky

	> export CROSS_COMPILE=arm-linux-gnueabi-
	> source oe-init-build-env build-atmel

	> vi conf/bblayers.conf

	> vi conf/local.conf

Modify the files regarding to the instructions from our GitHub page. You can of course use your preferred text editor. :-) Don't forget to set DISTRO ?= "poky-atmel" as mentioned in the text below the box.

	> bitbake atmel-xplained-demo-image

Here is the build log now.

     Build Configuration:
     BB_VERSION        = "1.32.0"
     BUILD_SYS         = "i686-linux"
     NATIVELSBSTRING   = "Ubuntu-16.04"
     TARGET_SYS        = "arm-poky-linux-gnueabi"
     MACHINE           = "sama5d3-xplained"
     DISTRO            = "poky-atmel"
     DISTRO_VERSION    = "2.2.4"
     TUNE_FEATURES     = "arm armv7a vfp thumb            callconvention-hard            cortexa5"
     TARGET_FPU        = "hard"
     meta
     meta-poky
     meta-yocto-bsp    = "morty:ccbb13fb661af127a6b2e3cc3d5fc44e84aa7dfe"
     meta-atmel        = "morty:3cf6c1f3b58add355791c1b92c0d98589b892eb1"
     meta-thornxt      = "morty:b0fb59176cda1feac3cea1c0c25dfcd7f3ac1dd3"
     meta-oe
     meta-networking
     meta-python       = "morty:997caf9146cd3797cd054e2adebd1fbb4df91911"
     meta-qt5          = "morty:f37449f25e3e58b76a64a4398d4f10ce7dc9206c"

Kind regards

Roy



Am 05.08.2018 um 10:03 schrieb Kechagias Apostolos:

**Comment by thorrockstar** [comment] 2018-08-05 16:45
Hi,

As my comments above have been send by e-mail, you might have noticed the lack of MarkDown formatting. :-)

Nevertheless, my build has now completed without any fault:

    Build Configuration:
    BB_VERSION        = "1.32.0"
    BUILD_SYS         = "i686-linux"
    NATIVELSBSTRING   = "Ubuntu-16.04"
    TARGET_SYS        = "arm-poky-linux-gnueabi"
    MACHINE           = "sama5d3-xplained"
    DISTRO            = "poky-atmel"
    DISTRO_VERSION    = "2.2.4"
    TUNE_FEATURES     = "arm armv7a vfp thumb            callconvention-hard            cortexa5"
    TARGET_FPU        = "hard"
    meta              
    meta-poky         
    meta-yocto-bsp    = "morty:ccbb13fb661af127a6b2e3cc3d5fc44e84aa7dfe"
    meta-atmel        = "morty:3cf6c1f3b58add355791c1b92c0d98589b892eb1"
    meta-thornxt      = "morty:b0fb59176cda1feac3cea1c0c25dfcd7f3ac1dd3"
    meta-oe           
    meta-networking   
    meta-python       = "morty:997caf9146cd3797cd054e2adebd1fbb4df91911"
    meta-qt5          = "morty:f37449f25e3e58b76a64a4398d4f10ce7dc9206c"
    
    Initialising tasks: 100% |    ##############################################################| Time: 0:00:06
    NOTE: Executing SetScene Tasks
    NOTE: Executing RunQueue Tasks
    NOTE: Tasks Summary: Attempted 3125 tasks of which 271 didn't need to be rerun and all succeeded.

**Closed as completed by thorrockstar** 2018-08-05 16:45 UTC

**Comment by kechap** [comment] 2018-08-05 16:56
The following line did the trick

`meta-thornxt      = "morty:b0fb59176cda1feac3cea1c0c25dfcd7f3ac1dd3"`

I was using the master branch as the README uses the latest available commit. 
Thanks.

**Comment by thorrockstar** [comment] 2018-08-05 17:45
Hi,

Thanks. In the README of the 'morty' branch was actually one '-b morty' missing.

Kind regards

**Comment by thorrockstar** [comment] 2018-08-05 22:50
Hi,

you have to re-build your image again.

I just spotted that distro 2.2.4 does *not* feature our kernel 
defconfig. Instead it uses the default Atmel defconfig. That means your 
SPI, SSM2218 and Timer Tick settings are wrong! Beside some other 
pre-settings as well. The board might boot but does not work as intended.

I just fixed that in the bitbake append file for 2.2.4 for the 'morty' 
branch. So please update your 'thor-nxt' layer and rebuild the image.

To double check if that 100% works, you can do a...

     bitbake linux-at91 -c menuconfig

...and check...

     General Setup -> Timer subsystem -> Timer Tick Handling (periodic)

...before building the image. Please give me some feedback if that 
worked for you.

Kind regards

Roy


Am 05.08.2018 um 18:56 schrieb Kechagias Apostolos:

**Comment by thorrockstar** [comment] 2018-08-06 00:18
Hi again,

by comparing the 2.2.2 and 2.2.4 distro build against each other I also 
noted a problem in the PAM authentication. I added a note and a patch to 
the README of the 'morty' branch. It seems only to be necessary starting 
with 2.2.4.

So you may encounter the problem that after bulding the image 'newusers' 
and 'chpassw' gives you an error in the way of:

    root@sama5d3-xplained:~# newusers
    newusers: PAM: Authentication failure
    root@sama5d3-xplained:~# chpasswd
    chpasswd: PAM: Authentication failure |

In that case you need to modify two files before building your image, by 
hand. You find them under '<Your Yocto folder>/poky/meta/recipes-extended/shadow/files/'.

     --- a/meta/recipes-extended/shadow/files/pam.d/chpasswd
     +++ b/meta/recipes-extended/shadow/files/pam.d/chpasswd
     @@ -1,4 +1,6 @@
     # The PAM configuration file for the Shadow 'chpasswd' service
     #
     +auth       sufficient   pam_rootok.so
     +account    required     pam_permit.so
      password   include      common-password

     --- a/meta/recipes-extended/shadow/files/pam.d/newusers
     +++ b/meta/recipes-extended/shadow/files/pam.d/newusers
     @@ -1,4 +1,6 @@
      # The PAM configuration file for the Shadow 'newusers' service
      #
    +auth       sufficient   pam_rootok.so
    +account    required     pam_permit.so
     password   include      common-password
